# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f822cbca6c675b8e4b58e6f86b16fa898211a64c5420101ff1da91549f89998b74ee8c6bf364dcf79585df60fb1ef840a8265c51ae8d09af1c3b03122ae8cfd9

test:
  secret_key_base: 0bf2d92d9adb4e9c96747ebe93d89deadf238a33ebe91383d03b4bec82a1f3d7efe2a194fdcbb9eeb7e07761c9cfe3b96e0a4479bcc155f33ddb97ca5c574bcc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
